# Generated by Django 5.2.15 on 2026-06-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='data',
        ),
    ]
