# Generated by Django 5.2.15 on 2026-06-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_album_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='hamsham',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='kol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='viral',
            field=models.FloatField(),
        ),
    ]
